// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type RegisterTrustedKeyCommand struct {
	PublicKey            *PublicKey `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterTrustedKeyCommand) Reset()         { *m = RegisterTrustedKeyCommand{} }
func (m *RegisterTrustedKeyCommand) String() string { return proto.CompactTextString(m) }
func (*RegisterTrustedKeyCommand) ProtoMessage()    {}
func (*RegisterTrustedKeyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *RegisterTrustedKeyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTrustedKeyCommand.Unmarshal(m, b)
}
func (m *RegisterTrustedKeyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTrustedKeyCommand.Marshal(b, m, deterministic)
}
func (m *RegisterTrustedKeyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTrustedKeyCommand.Merge(m, src)
}
func (m *RegisterTrustedKeyCommand) XXX_Size() int {
	return xxx_messageInfo_RegisterTrustedKeyCommand.Size(m)
}
func (m *RegisterTrustedKeyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTrustedKeyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTrustedKeyCommand proto.InternalMessageInfo

func (m *RegisterTrustedKeyCommand) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type RegisterKeyManagerCommand struct {
	PublicKey            *PublicKey `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterKeyManagerCommand) Reset()         { *m = RegisterKeyManagerCommand{} }
func (m *RegisterKeyManagerCommand) String() string { return proto.CompactTextString(m) }
func (*RegisterKeyManagerCommand) ProtoMessage()    {}
func (*RegisterKeyManagerCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *RegisterKeyManagerCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterKeyManagerCommand.Unmarshal(m, b)
}
func (m *RegisterKeyManagerCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterKeyManagerCommand.Marshal(b, m, deterministic)
}
func (m *RegisterKeyManagerCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterKeyManagerCommand.Merge(m, src)
}
func (m *RegisterKeyManagerCommand) XXX_Size() int {
	return xxx_messageInfo_RegisterKeyManagerCommand.Size(m)
}
func (m *RegisterKeyManagerCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterKeyManagerCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterKeyManagerCommand proto.InternalMessageInfo

func (m *RegisterKeyManagerCommand) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type RegisterCredentialsCommand struct {
	Credentials          *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterCredentialsCommand) Reset()         { *m = RegisterCredentialsCommand{} }
func (m *RegisterCredentialsCommand) String() string { return proto.CompactTextString(m) }
func (*RegisterCredentialsCommand) ProtoMessage()    {}
func (*RegisterCredentialsCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}

func (m *RegisterCredentialsCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCredentialsCommand.Unmarshal(m, b)
}
func (m *RegisterCredentialsCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCredentialsCommand.Marshal(b, m, deterministic)
}
func (m *RegisterCredentialsCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCredentialsCommand.Merge(m, src)
}
func (m *RegisterCredentialsCommand) XXX_Size() int {
	return xxx_messageInfo_RegisterCredentialsCommand.Size(m)
}
func (m *RegisterCredentialsCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCredentialsCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCredentialsCommand proto.InternalMessageInfo

func (m *RegisterCredentialsCommand) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type ChangePropertyCommand struct {
	Property             *KeyValue `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ChangePropertyCommand) Reset()         { *m = ChangePropertyCommand{} }
func (m *ChangePropertyCommand) String() string { return proto.CompactTextString(m) }
func (*ChangePropertyCommand) ProtoMessage()    {}
func (*ChangePropertyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{4}
}

func (m *ChangePropertyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePropertyCommand.Unmarshal(m, b)
}
func (m *ChangePropertyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePropertyCommand.Marshal(b, m, deterministic)
}
func (m *ChangePropertyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePropertyCommand.Merge(m, src)
}
func (m *ChangePropertyCommand) XXX_Size() int {
	return xxx_messageInfo_ChangePropertyCommand.Size(m)
}
func (m *ChangePropertyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePropertyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePropertyCommand proto.InternalMessageInfo

func (m *ChangePropertyCommand) GetProperty() *KeyValue {
	if m != nil {
		return m.Property
	}
	return nil
}

type TrustedKeyAddedEvent struct {
	PublicKey            *PublicKey `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TrustedKeyAddedEvent) Reset()         { *m = TrustedKeyAddedEvent{} }
func (m *TrustedKeyAddedEvent) String() string { return proto.CompactTextString(m) }
func (*TrustedKeyAddedEvent) ProtoMessage()    {}
func (*TrustedKeyAddedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{5}
}

func (m *TrustedKeyAddedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustedKeyAddedEvent.Unmarshal(m, b)
}
func (m *TrustedKeyAddedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustedKeyAddedEvent.Marshal(b, m, deterministic)
}
func (m *TrustedKeyAddedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustedKeyAddedEvent.Merge(m, src)
}
func (m *TrustedKeyAddedEvent) XXX_Size() int {
	return xxx_messageInfo_TrustedKeyAddedEvent.Size(m)
}
func (m *TrustedKeyAddedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustedKeyAddedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TrustedKeyAddedEvent proto.InternalMessageInfo

func (m *TrustedKeyAddedEvent) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type TrustedKeyRemovedEvent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrustedKeyRemovedEvent) Reset()         { *m = TrustedKeyRemovedEvent{} }
func (m *TrustedKeyRemovedEvent) String() string { return proto.CompactTextString(m) }
func (*TrustedKeyRemovedEvent) ProtoMessage()    {}
func (*TrustedKeyRemovedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{6}
}

func (m *TrustedKeyRemovedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustedKeyRemovedEvent.Unmarshal(m, b)
}
func (m *TrustedKeyRemovedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustedKeyRemovedEvent.Marshal(b, m, deterministic)
}
func (m *TrustedKeyRemovedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustedKeyRemovedEvent.Merge(m, src)
}
func (m *TrustedKeyRemovedEvent) XXX_Size() int {
	return xxx_messageInfo_TrustedKeyRemovedEvent.Size(m)
}
func (m *TrustedKeyRemovedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustedKeyRemovedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TrustedKeyRemovedEvent proto.InternalMessageInfo

func (m *TrustedKeyRemovedEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type KeyManagerAddedEvent struct {
	PublicKey            *PublicKey `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *KeyManagerAddedEvent) Reset()         { *m = KeyManagerAddedEvent{} }
func (m *KeyManagerAddedEvent) String() string { return proto.CompactTextString(m) }
func (*KeyManagerAddedEvent) ProtoMessage()    {}
func (*KeyManagerAddedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{7}
}

func (m *KeyManagerAddedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyManagerAddedEvent.Unmarshal(m, b)
}
func (m *KeyManagerAddedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyManagerAddedEvent.Marshal(b, m, deterministic)
}
func (m *KeyManagerAddedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyManagerAddedEvent.Merge(m, src)
}
func (m *KeyManagerAddedEvent) XXX_Size() int {
	return xxx_messageInfo_KeyManagerAddedEvent.Size(m)
}
func (m *KeyManagerAddedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyManagerAddedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_KeyManagerAddedEvent proto.InternalMessageInfo

func (m *KeyManagerAddedEvent) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type KeyManagerRemovedEvent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyManagerRemovedEvent) Reset()         { *m = KeyManagerRemovedEvent{} }
func (m *KeyManagerRemovedEvent) String() string { return proto.CompactTextString(m) }
func (*KeyManagerRemovedEvent) ProtoMessage()    {}
func (*KeyManagerRemovedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{8}
}

func (m *KeyManagerRemovedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyManagerRemovedEvent.Unmarshal(m, b)
}
func (m *KeyManagerRemovedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyManagerRemovedEvent.Marshal(b, m, deterministic)
}
func (m *KeyManagerRemovedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyManagerRemovedEvent.Merge(m, src)
}
func (m *KeyManagerRemovedEvent) XXX_Size() int {
	return xxx_messageInfo_KeyManagerRemovedEvent.Size(m)
}
func (m *KeyManagerRemovedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyManagerRemovedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_KeyManagerRemovedEvent proto.InternalMessageInfo

func (m *KeyManagerRemovedEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CredentialsAddedEvent struct {
	Credentials          *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CredentialsAddedEvent) Reset()         { *m = CredentialsAddedEvent{} }
func (m *CredentialsAddedEvent) String() string { return proto.CompactTextString(m) }
func (*CredentialsAddedEvent) ProtoMessage()    {}
func (*CredentialsAddedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{9}
}

func (m *CredentialsAddedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialsAddedEvent.Unmarshal(m, b)
}
func (m *CredentialsAddedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialsAddedEvent.Marshal(b, m, deterministic)
}
func (m *CredentialsAddedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialsAddedEvent.Merge(m, src)
}
func (m *CredentialsAddedEvent) XXX_Size() int {
	return xxx_messageInfo_CredentialsAddedEvent.Size(m)
}
func (m *CredentialsAddedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialsAddedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialsAddedEvent proto.InternalMessageInfo

func (m *CredentialsAddedEvent) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type CredentialsRemovedEvent struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialsRemovedEvent) Reset()         { *m = CredentialsRemovedEvent{} }
func (m *CredentialsRemovedEvent) String() string { return proto.CompactTextString(m) }
func (*CredentialsRemovedEvent) ProtoMessage()    {}
func (*CredentialsRemovedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{10}
}

func (m *CredentialsRemovedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialsRemovedEvent.Unmarshal(m, b)
}
func (m *CredentialsRemovedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialsRemovedEvent.Marshal(b, m, deterministic)
}
func (m *CredentialsRemovedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialsRemovedEvent.Merge(m, src)
}
func (m *CredentialsRemovedEvent) XXX_Size() int {
	return xxx_messageInfo_CredentialsRemovedEvent.Size(m)
}
func (m *CredentialsRemovedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialsRemovedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialsRemovedEvent proto.InternalMessageInfo

func (m *CredentialsRemovedEvent) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type PropertyChangedEvent struct {
	Property             *KeyValue `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PropertyChangedEvent) Reset()         { *m = PropertyChangedEvent{} }
func (m *PropertyChangedEvent) String() string { return proto.CompactTextString(m) }
func (*PropertyChangedEvent) ProtoMessage()    {}
func (*PropertyChangedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{11}
}

func (m *PropertyChangedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyChangedEvent.Unmarshal(m, b)
}
func (m *PropertyChangedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyChangedEvent.Marshal(b, m, deterministic)
}
func (m *PropertyChangedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyChangedEvent.Merge(m, src)
}
func (m *PropertyChangedEvent) XXX_Size() int {
	return xxx_messageInfo_PropertyChangedEvent.Size(m)
}
func (m *PropertyChangedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyChangedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyChangedEvent proto.InternalMessageInfo

func (m *PropertyChangedEvent) GetProperty() *KeyValue {
	if m != nil {
		return m.Property
	}
	return nil
}

type PublicKey struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{12}
}

func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (m *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(m, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *PublicKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PrivateKey struct {
	PrivateKey           string   `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKey) Reset()         { *m = PrivateKey{} }
func (m *PrivateKey) String() string { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()    {}
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{13}
}

func (m *PrivateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKey.Unmarshal(m, b)
}
func (m *PrivateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKey.Marshal(b, m, deterministic)
}
func (m *PrivateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKey.Merge(m, src)
}
func (m *PrivateKey) XXX_Size() int {
	return xxx_messageInfo_PrivateKey.Size(m)
}
func (m *PrivateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKey.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKey proto.InternalMessageInfo

func (m *PrivateKey) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *PrivateKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AccessToken struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{14}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type TrustedKeyRequest struct {
	PublicKey            *PublicKey `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Nonce                []byte     `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature            *Signature `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	IsKeyManager         bool       `protobuf:"varint,5,opt,name=isKeyManager,proto3" json:"isKeyManager,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TrustedKeyRequest) Reset()         { *m = TrustedKeyRequest{} }
func (m *TrustedKeyRequest) String() string { return proto.CompactTextString(m) }
func (*TrustedKeyRequest) ProtoMessage()    {}
func (*TrustedKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{15}
}

func (m *TrustedKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustedKeyRequest.Unmarshal(m, b)
}
func (m *TrustedKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustedKeyRequest.Marshal(b, m, deterministic)
}
func (m *TrustedKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustedKeyRequest.Merge(m, src)
}
func (m *TrustedKeyRequest) XXX_Size() int {
	return xxx_messageInfo_TrustedKeyRequest.Size(m)
}
func (m *TrustedKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustedKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrustedKeyRequest proto.InternalMessageInfo

func (m *TrustedKeyRequest) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *TrustedKeyRequest) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *TrustedKeyRequest) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TrustedKeyRequest) GetIsKeyManager() bool {
	if m != nil {
		return m.IsKeyManager
	}
	return false
}

type TrustedKeyResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Nonce                []byte   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrustedKeyResponse) Reset()         { *m = TrustedKeyResponse{} }
func (m *TrustedKeyResponse) String() string { return proto.CompactTextString(m) }
func (*TrustedKeyResponse) ProtoMessage()    {}
func (*TrustedKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{16}
}

func (m *TrustedKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustedKeyResponse.Unmarshal(m, b)
}
func (m *TrustedKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustedKeyResponse.Marshal(b, m, deterministic)
}
func (m *TrustedKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustedKeyResponse.Merge(m, src)
}
func (m *TrustedKeyResponse) XXX_Size() int {
	return xxx_messageInfo_TrustedKeyResponse.Size(m)
}
func (m *TrustedKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustedKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrustedKeyResponse proto.InternalMessageInfo

func (m *TrustedKeyResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *TrustedKeyResponse) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type Signature struct {
	Format               string   `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Blob                 []byte   `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	Rest                 []byte   `protobuf:"bytes,3,opt,name=rest,proto3" json:"rest,omitempty"`
	SignatureName        string   `protobuf:"bytes,4,opt,name=signatureName,proto3" json:"signatureName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{17}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Signature) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

func (m *Signature) GetRest() []byte {
	if m != nil {
		return m.Rest
	}
	return nil
}

func (m *Signature) GetSignatureName() string {
	if m != nil {
		return m.SignatureName
	}
	return ""
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{18}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Credentials struct {
	Identifier           string     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Secret               string     `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Signature            *Signature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{19}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Credentials) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Credentials) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{20}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "org.leialearns.grpc.example.Empty")
	proto.RegisterType((*RegisterTrustedKeyCommand)(nil), "org.leialearns.grpc.example.RegisterTrustedKeyCommand")
	proto.RegisterType((*RegisterKeyManagerCommand)(nil), "org.leialearns.grpc.example.RegisterKeyManagerCommand")
	proto.RegisterType((*RegisterCredentialsCommand)(nil), "org.leialearns.grpc.example.RegisterCredentialsCommand")
	proto.RegisterType((*ChangePropertyCommand)(nil), "org.leialearns.grpc.example.ChangePropertyCommand")
	proto.RegisterType((*TrustedKeyAddedEvent)(nil), "org.leialearns.grpc.example.TrustedKeyAddedEvent")
	proto.RegisterType((*TrustedKeyRemovedEvent)(nil), "org.leialearns.grpc.example.TrustedKeyRemovedEvent")
	proto.RegisterType((*KeyManagerAddedEvent)(nil), "org.leialearns.grpc.example.KeyManagerAddedEvent")
	proto.RegisterType((*KeyManagerRemovedEvent)(nil), "org.leialearns.grpc.example.KeyManagerRemovedEvent")
	proto.RegisterType((*CredentialsAddedEvent)(nil), "org.leialearns.grpc.example.CredentialsAddedEvent")
	proto.RegisterType((*CredentialsRemovedEvent)(nil), "org.leialearns.grpc.example.CredentialsRemovedEvent")
	proto.RegisterType((*PropertyChangedEvent)(nil), "org.leialearns.grpc.example.PropertyChangedEvent")
	proto.RegisterType((*PublicKey)(nil), "org.leialearns.grpc.example.PublicKey")
	proto.RegisterType((*PrivateKey)(nil), "org.leialearns.grpc.example.PrivateKey")
	proto.RegisterType((*AccessToken)(nil), "org.leialearns.grpc.example.AccessToken")
	proto.RegisterType((*TrustedKeyRequest)(nil), "org.leialearns.grpc.example.TrustedKeyRequest")
	proto.RegisterType((*TrustedKeyResponse)(nil), "org.leialearns.grpc.example.TrustedKeyResponse")
	proto.RegisterType((*Signature)(nil), "org.leialearns.grpc.example.Signature")
	proto.RegisterType((*Status)(nil), "org.leialearns.grpc.example.Status")
	proto.RegisterType((*Credentials)(nil), "org.leialearns.grpc.example.Credentials")
	proto.RegisterType((*KeyValue)(nil), "org.leialearns.grpc.example.KeyValue")
}

func init() {
	proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6)
}

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xeb, 0x6a, 0x13, 0x41,
	0x14, 0xce, 0xda, 0x24, 0x6d, 0x4e, 0x5a, 0xb5, 0x43, 0x5a, 0x63, 0x94, 0x5a, 0xc6, 0x5b, 0x7e,
	0x48, 0x52, 0x2a, 0x08, 0x22, 0x82, 0xb1, 0x16, 0xc1, 0xa8, 0x94, 0x6d, 0x11, 0x2c, 0x22, 0x4c,
	0x36, 0xa7, 0xdb, 0xb5, 0xd9, 0x4b, 0x67, 0x66, 0xa3, 0xe9, 0x2b, 0xf8, 0x84, 0x3e, 0x88, 0xff,
	0x65, 0xf6, 0x3a, 0xd5, 0xb2, 0x5d, 0x25, 0xfe, 0x9b, 0x39, 0x73, 0xce, 0xf7, 0x9d, 0xcb, 0x37,
	0xb3, 0x0b, 0x2b, 0xf8, 0x8d, 0xb9, 0xc1, 0x04, 0x7b, 0x01, 0xf7, 0xa5, 0x4f, 0x6e, 0xf9, 0xdc,
	0xee, 0x4d, 0xd0, 0x61, 0x13, 0x64, 0xdc, 0x13, 0x3d, 0x9b, 0x07, 0x56, 0x2f, 0x71, 0xa1, 0x8b,
	0x50, 0xdb, 0x75, 0x03, 0x39, 0xa3, 0x0c, 0x6e, 0x9a, 0x68, 0x3b, 0x42, 0x22, 0x3f, 0xe0, 0xa1,
	0x90, 0x38, 0x1e, 0xe2, 0x6c, 0xc7, 0x77, 0x5d, 0xe6, 0x8d, 0xc9, 0x2b, 0x68, 0x04, 0xe1, 0x68,
	0xe2, 0x58, 0x43, 0x9c, 0xb5, 0x8d, 0x4d, 0xa3, 0xdb, 0xdc, 0x7e, 0xd0, 0x2b, 0x80, 0xed, 0xed,
	0xa5, 0xde, 0x66, 0x1e, 0xa8, 0x53, 0x0c, 0x71, 0xf6, 0x8e, 0x79, 0xcc, 0x46, 0x3e, 0x5f, 0x8a,
	0x63, 0xe8, 0xa4, 0x14, 0x3b, 0x1c, 0xc7, 0xe8, 0x49, 0x87, 0x4d, 0x44, 0xca, 0xf1, 0x06, 0x9a,
	0x56, 0x6e, 0x4d, 0x58, 0xba, 0x85, 0x2c, 0x1a, 0x8a, 0xa9, 0x07, 0xd3, 0x43, 0x58, 0xdb, 0x39,
	0x66, 0x9e, 0x8d, 0x7b, 0xdc, 0x0f, 0x90, 0xcb, 0xac, 0x57, 0x03, 0x58, 0x0a, 0x12, 0x53, 0xc2,
	0x70, 0xbf, 0x90, 0x61, 0x88, 0xb3, 0x0f, 0x6c, 0x12, 0xa2, 0x99, 0x85, 0xd1, 0x4f, 0xd0, 0xca,
	0x67, 0x30, 0x18, 0x8f, 0x71, 0xbc, 0x3b, 0x45, 0x4f, 0xce, 0xa9, 0x47, 0x8f, 0x60, 0x3d, 0x47,
	0x37, 0xd1, 0xf5, 0xa7, 0x29, 0x3e, 0x81, 0xaa, 0xc7, 0x5c, 0x8c, 0xa0, 0x1b, 0x66, 0xb4, 0x56,
	0xb9, 0xe4, 0xc3, 0xfa, 0x1f, 0xb9, 0xe4, 0xe8, 0x97, 0xe6, 0x62, 0xc1, 0x9a, 0x36, 0x0f, 0x2d,
	0x99, 0x79, 0x0e, 0xf6, 0x29, 0xdc, 0xd0, 0xcf, 0xf4, 0x9c, 0x36, 0x00, 0x9c, 0xe8, 0xe0, 0xc8,
	0x41, 0x9e, 0x64, 0xa6, 0x59, 0xe8, 0x47, 0x68, 0x65, 0x6a, 0x88, 0xb4, 0x91, 0xc4, 0xcd, 0x41,
	0x12, 0xcf, 0xa1, 0x91, 0x35, 0x90, 0xdc, 0xfe, 0xbd, 0xf7, 0x0d, 0xad, 0xa7, 0x59, 0xe7, 0xae,
	0x68, 0x9d, 0x7b, 0x01, 0xb0, 0xc7, 0x9d, 0x29, 0x93, 0xa8, 0x3c, 0x36, 0x00, 0x82, 0x6c, 0x97,
	0xd6, 0x91, 0x5b, 0x2e, 0x44, 0xb8, 0x03, 0xcd, 0x81, 0x65, 0xa1, 0x10, 0x07, 0xfe, 0x09, 0x7a,
	0xe4, 0x3a, 0x2c, 0x7c, 0xf9, 0x2a, 0x93, 0x58, 0xb5, 0xa4, 0x3f, 0x0c, 0x58, 0xd5, 0x75, 0x75,
	0x1a, 0xa2, 0x98, 0x93, 0x4c, 0x48, 0x0b, 0x6a, 0x9e, 0xef, 0x59, 0x71, 0x46, 0xcb, 0x66, 0xbc,
	0x51, 0xd8, 0xc2, 0xb1, 0x3d, 0x26, 0x43, 0x8e, 0xed, 0x6a, 0x09, 0xec, 0xfd, 0xd4, 0xdb, 0xcc,
	0x03, 0x09, 0x85, 0x65, 0x47, 0xe4, 0x22, 0x6c, 0xd7, 0x36, 0x8d, 0xee, 0x92, 0x79, 0xce, 0x46,
	0x6d, 0x20, 0x7a, 0x69, 0x22, 0xf0, 0x3d, 0x81, 0xe4, 0x19, 0xd4, 0x85, 0x64, 0x32, 0x4c, 0x05,
	0x77, 0xb7, 0x98, 0x3c, 0x72, 0x35, 0x93, 0x90, 0x8b, 0x4b, 0xa2, 0xa7, 0xd0, 0xc8, 0x92, 0x24,
	0xeb, 0x50, 0x3f, 0xf2, 0xb9, 0xcb, 0xd2, 0x36, 0x27, 0x3b, 0x35, 0x9e, 0xd1, 0xc4, 0x1f, 0x25,
	0x91, 0xd1, 0x5a, 0xd9, 0x38, 0x0a, 0xd9, 0x5e, 0x88, 0x6d, 0x6a, 0x4d, 0xee, 0xc1, 0x4a, 0x56,
	0xe6, 0x7b, 0x35, 0xcf, 0x6a, 0x04, 0x73, 0xde, 0x48, 0x9f, 0x40, 0x3d, 0x4e, 0x4d, 0x61, 0x58,
	0xfe, 0x38, 0xbe, 0x72, 0x35, 0x33, 0x5a, 0x93, 0x36, 0x2c, 0xba, 0x28, 0x04, 0xb3, 0x53, 0x35,
	0xa4, 0x5b, 0xfa, 0xdd, 0x80, 0xa6, 0x76, 0x51, 0x2e, 0xbb, 0x1c, 0xaa, 0x1a, 0x81, 0x16, 0x47,
	0x99, 0x00, 0x25, 0xbb, 0xf3, 0x53, 0x5c, 0xf8, 0xc7, 0x29, 0xd2, 0x6d, 0x58, 0x4a, 0x6f, 0x8d,
	0xd2, 0xe6, 0x49, 0xa6, 0x6b, 0xb5, 0x54, 0xcd, 0x9e, 0xaa, 0xa3, 0x84, 0x3a, 0xde, 0x6c, 0xff,
	0xac, 0xc2, 0xd5, 0xd7, 0x1c, 0x51, 0x22, 0xdf, 0x47, 0x3e, 0x75, 0x2c, 0x24, 0x0c, 0xae, 0xbd,
	0x75, 0x84, 0xcc, 0x87, 0x2d, 0x08, 0x2d, 0x4c, 0x26, 0xfa, 0x78, 0x76, 0x4a, 0x4a, 0x9a, 0x56,
	0xb6, 0x0c, 0x72, 0x06, 0xab, 0xf1, 0xe3, 0xa0, 0x93, 0xf4, 0x0a, 0x01, 0xfe, 0xb8, 0x56, 0x9d,
	0x7e, 0x69, 0xff, 0x58, 0xab, 0xb4, 0xd2, 0x35, 0xb6, 0x0c, 0xf2, 0x19, 0x56, 0xf6, 0x51, 0x6a,
	0x2f, 0xc1, 0xc3, 0xe2, 0xc4, 0x33, 0xc7, 0x4e, 0x89, 0x2e, 0xd0, 0x0a, 0xc1, 0xb4, 0x36, 0x5d,
	0x18, 0xa5, 0xdf, 0xe1, 0x72, 0x24, 0x5d, 0x83, 0x30, 0x68, 0x0c, 0x42, 0x79, 0xec, 0x73, 0xe7,
	0x0c, 0xff, 0x02, 0xbe, 0xd8, 0x53, 0x7b, 0xdd, 0x68, 0x85, 0x1c, 0x42, 0x33, 0xea, 0x54, 0xfc,
	0xfc, 0x92, 0x72, 0xef, 0x75, 0xb9, 0x02, 0x5e, 0xae, 0x1f, 0xb6, 0x04, 0xb7, 0xfa, 0xc1, 0x89,
	0xdd, 0x57, 0xe7, 0xfd, 0xe4, 0x7c, 0x54, 0x8f, 0xfe, 0xd7, 0x1e, 0xff, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x3b, 0xa3, 0xc6, 0x50, 0xc0, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterServiceClient is the client API for GreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterServiceClient interface {
	ListTrustedKeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (GreeterService_ListTrustedKeysClient, error)
	ChangeTrustedKeys(ctx context.Context, opts ...grpc.CallOption) (GreeterService_ChangeTrustedKeysClient, error)
	SetPrivateKey(ctx context.Context, in *PrivateKey, opts ...grpc.CallOption) (*Empty, error)
	ChangeCredentials(ctx context.Context, opts ...grpc.CallOption) (GreeterService_ChangeCredentialsClient, error)
	Authorize(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*AccessToken, error)
	SetProperty(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Empty, error)
}

type greeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterServiceClient(cc grpc.ClientConnInterface) GreeterServiceClient {
	return &greeterServiceClient{cc}
}

func (c *greeterServiceClient) ListTrustedKeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (GreeterService_ListTrustedKeysClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreeterService_serviceDesc.Streams[0], "/org.leialearns.grpc.example.GreeterService/ListTrustedKeys", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServiceListTrustedKeysClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreeterService_ListTrustedKeysClient interface {
	Recv() (*PublicKey, error)
	grpc.ClientStream
}

type greeterServiceListTrustedKeysClient struct {
	grpc.ClientStream
}

func (x *greeterServiceListTrustedKeysClient) Recv() (*PublicKey, error) {
	m := new(PublicKey)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterServiceClient) ChangeTrustedKeys(ctx context.Context, opts ...grpc.CallOption) (GreeterService_ChangeTrustedKeysClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreeterService_serviceDesc.Streams[1], "/org.leialearns.grpc.example.GreeterService/ChangeTrustedKeys", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServiceChangeTrustedKeysClient{stream}
	return x, nil
}

type GreeterService_ChangeTrustedKeysClient interface {
	Send(*TrustedKeyRequest) error
	Recv() (*TrustedKeyResponse, error)
	grpc.ClientStream
}

type greeterServiceChangeTrustedKeysClient struct {
	grpc.ClientStream
}

func (x *greeterServiceChangeTrustedKeysClient) Send(m *TrustedKeyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterServiceChangeTrustedKeysClient) Recv() (*TrustedKeyResponse, error) {
	m := new(TrustedKeyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterServiceClient) SetPrivateKey(ctx context.Context, in *PrivateKey, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/org.leialearns.grpc.example.GreeterService/SetPrivateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) ChangeCredentials(ctx context.Context, opts ...grpc.CallOption) (GreeterService_ChangeCredentialsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreeterService_serviceDesc.Streams[2], "/org.leialearns.grpc.example.GreeterService/ChangeCredentials", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServiceChangeCredentialsClient{stream}
	return x, nil
}

type GreeterService_ChangeCredentialsClient interface {
	Send(*Credentials) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type greeterServiceChangeCredentialsClient struct {
	grpc.ClientStream
}

func (x *greeterServiceChangeCredentialsClient) Send(m *Credentials) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterServiceChangeCredentialsClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterServiceClient) Authorize(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*AccessToken, error) {
	out := new(AccessToken)
	err := c.cc.Invoke(ctx, "/org.leialearns.grpc.example.GreeterService/Authorize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) SetProperty(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/org.leialearns.grpc.example.GreeterService/SetProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServiceServer is the server API for GreeterService service.
type GreeterServiceServer interface {
	ListTrustedKeys(*Empty, GreeterService_ListTrustedKeysServer) error
	ChangeTrustedKeys(GreeterService_ChangeTrustedKeysServer) error
	SetPrivateKey(context.Context, *PrivateKey) (*Empty, error)
	ChangeCredentials(GreeterService_ChangeCredentialsServer) error
	Authorize(context.Context, *Credentials) (*AccessToken, error)
	SetProperty(context.Context, *KeyValue) (*Empty, error)
}

// UnimplementedGreeterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServiceServer struct {
}

func (*UnimplementedGreeterServiceServer) ListTrustedKeys(req *Empty, srv GreeterService_ListTrustedKeysServer) error {
	return status.Errorf(codes.Unimplemented, "method ListTrustedKeys not implemented")
}
func (*UnimplementedGreeterServiceServer) ChangeTrustedKeys(srv GreeterService_ChangeTrustedKeysServer) error {
	return status.Errorf(codes.Unimplemented, "method ChangeTrustedKeys not implemented")
}
func (*UnimplementedGreeterServiceServer) SetPrivateKey(ctx context.Context, req *PrivateKey) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrivateKey not implemented")
}
func (*UnimplementedGreeterServiceServer) ChangeCredentials(srv GreeterService_ChangeCredentialsServer) error {
	return status.Errorf(codes.Unimplemented, "method ChangeCredentials not implemented")
}
func (*UnimplementedGreeterServiceServer) Authorize(ctx context.Context, req *Credentials) (*AccessToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorize not implemented")
}
func (*UnimplementedGreeterServiceServer) SetProperty(ctx context.Context, req *KeyValue) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProperty not implemented")
}

func RegisterGreeterServiceServer(s *grpc.Server, srv GreeterServiceServer) {
	s.RegisterService(&_GreeterService_serviceDesc, srv)
}

func _GreeterService_ListTrustedKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServiceServer).ListTrustedKeys(m, &greeterServiceListTrustedKeysServer{stream})
}

type GreeterService_ListTrustedKeysServer interface {
	Send(*PublicKey) error
	grpc.ServerStream
}

type greeterServiceListTrustedKeysServer struct {
	grpc.ServerStream
}

func (x *greeterServiceListTrustedKeysServer) Send(m *PublicKey) error {
	return x.ServerStream.SendMsg(m)
}

func _GreeterService_ChangeTrustedKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServiceServer).ChangeTrustedKeys(&greeterServiceChangeTrustedKeysServer{stream})
}

type GreeterService_ChangeTrustedKeysServer interface {
	Send(*TrustedKeyResponse) error
	Recv() (*TrustedKeyRequest, error)
	grpc.ServerStream
}

type greeterServiceChangeTrustedKeysServer struct {
	grpc.ServerStream
}

func (x *greeterServiceChangeTrustedKeysServer) Send(m *TrustedKeyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterServiceChangeTrustedKeysServer) Recv() (*TrustedKeyRequest, error) {
	m := new(TrustedKeyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreeterService_SetPrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).SetPrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.leialearns.grpc.example.GreeterService/SetPrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).SetPrivateKey(ctx, req.(*PrivateKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_ChangeCredentials_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServiceServer).ChangeCredentials(&greeterServiceChangeCredentialsServer{stream})
}

type GreeterService_ChangeCredentialsServer interface {
	SendAndClose(*Empty) error
	Recv() (*Credentials, error)
	grpc.ServerStream
}

type greeterServiceChangeCredentialsServer struct {
	grpc.ServerStream
}

func (x *greeterServiceChangeCredentialsServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterServiceChangeCredentialsServer) Recv() (*Credentials, error) {
	m := new(Credentials)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreeterService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.leialearns.grpc.example.GreeterService/Authorize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).Authorize(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_SetProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).SetProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.leialearns.grpc.example.GreeterService/SetProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).SetProperty(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreeterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "org.leialearns.grpc.example.GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetPrivateKey",
			Handler:    _GreeterService_SetPrivateKey_Handler,
		},
		{
			MethodName: "Authorize",
			Handler:    _GreeterService_Authorize_Handler,
		},
		{
			MethodName: "SetProperty",
			Handler:    _GreeterService_SetProperty_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListTrustedKeys",
			Handler:       _GreeterService_ListTrustedKeys_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChangeTrustedKeys",
			Handler:       _GreeterService_ChangeTrustedKeys_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ChangeCredentials",
			Handler:       _GreeterService_ChangeCredentials_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "example.proto",
}
