version: '3.7'

networks:
  ${ENSEMBLE_NAME}:
    driver: overlay

services:
  axon-server:
    image: axoniq/axonserver:${AXON_VERSION}
    init: true
    networks:
    - ${ENSEMBLE_NAME}
    ports:
    - target: 8024
      published: ${AXON_SERVER_PORT}
    expose:
    - "8024"
    - "8124"
    volumes:
    -
      type: volume
      source: axon-data
      target: /data
    -
      type: volume
      source: axon-eventdata
      target: /eventdata
  command-api:
    image: ${DOCKER_REPOSITORY}/archetype-go-axon
    working_dir: ${PROJECT}
    command:
      - "target/bin/example"
    init: true
    hostname: command-api
    networks:
    - ${ENSEMBLE_NAME}
    ports:
    - target: 8181
      published: ${API_SERVER_PORT}
    depends_on:
    - axon-server
    volumes:
      - type: volume
        source: ${NIX_STORE_VOLUME}
        target: /nix/store
      #${EXTRA_VOLUMES}
  proxy:
    image: ${DOCKER_REPOSITORY}/proxy:${IMAGE_VERSION}
    networks:
      - ${ENSEMBLE_NAME}
    ports:
      - target: 80
        published: ${UI_SERVER_PORT}
    depends_on:
      - command-api
      - axon-server
  grpc-swagger:
    image: ${DOCKER_REPOSITORY}/grpc-swagger
    networks:
      - ${ENSEMBLE_NAME}
    ports:
      - target: '8080'
        published: '8123'

volumes:
  axon-data:
  axon-eventdata:
  elastic-search-data:
  ${NIX_STORE_VOLUME}:
    external: true

